[package]
name = "register-node"
version = "0.1.0"
authors = ["Belson Heng"]

[[bin]]
name = "register-node-alpha"
path = "src/main.rs"

[dependencies]
regex = "1.0.0"
reqwest = "0.8.6"
serde_json = "1.0"
log = "0.4.0"
log4rs = "0.8.0"
